BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        id: clearButton
        text: 'Clear'
        on_release: app.press_clear()
#    Button:
#        text: 'two'
    TextInput:
        id: input_name
        text: ''
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        text: 'Enter your name'
        color: (1, 1, 0, 1)
        id: output_label
